CXX = g++
CXXFLAGS = -std=c++17 -Wall -Wextra
DEPFLAGS = -MMD -MP

# Debug target flags (AddressSanitizer helps find memory errors)
DEBUG_FLAGS = -g -O0 -fsanitize=address,undefined

LDFLAGS = -lsfml-graphics -lsfml-window -lsfml-system -lsfml-audio
SRC_DIR = src
BIN_DIR = bin
INCLUDE_DIR = include

# Lista explícita de archivos fuente a compilar
SOURCES = $(SRC_DIR)/main.cpp $(SRC_DIR)/Game.cpp $(SRC_DIR)/Fondo.cpp $(SRC_DIR)/SpriteJugador.cpp $(SRC_DIR)/02_Enemigo.cpp $(SRC_DIR)/SoundManager.cpp $(SRC_DIR)/Button.cpp $(SRC_DIR)/MenuElement.cpp $(SRC_DIR)/Menu.cpp
OBJECTS = $(SOURCES:$(SRC_DIR)/%.cpp=$(BIN_DIR)/%.o)

# Crear directorio bin si no existe
$(BIN_DIR):
	mkdir -p $(BIN_DIR)

# Regla principal
all: $(BIN_DIR)/main.exe

# Include dependency files generated by the compiler
-include $(OBJECTS:.o=.d)

# Enlazar objetos
$(BIN_DIR)/main.exe: $(OBJECTS) | $(BIN_DIR)
	$(CXX) $(OBJECTS) -o $@ $(LDFLAGS)

# Compilar .cpp a .o and generate header dependency files
$(BIN_DIR)/%.o: $(SRC_DIR)/%.cpp | $(BIN_DIR)
	$(CXX) $(CXXFLAGS) $(DEPFLAGS) -I$(INCLUDE_DIR) -c $< -o $@

# Limpiar
clean:
	rm -rf $(BIN_DIR)

# Ejecutar el programa principal
run: $(BIN_DIR)/main.exe
	./$<

# Compilar y ejecutar 00_Fondo.cpp
fondo: $(BIN_DIR)/fondo.exe

$(BIN_DIR)/fondo.exe: $(SRC_DIR)/00_Fondo.cpp $(SRC_DIR)/Fondo.cpp | $(BIN_DIR)
	$(CXX) $(CXXFLAGS) -I$(INCLUDE_DIR) $^ -o $@ $(LDFLAGS)

run_fondo: fondo
	./$(BIN_DIR)/fondo.exe

# Compilar y ejecutar 01_SpriteJugador.cpp
sprite: $(BIN_DIR)/sprite.exe

$(BIN_DIR)/sprite.exe: $(SRC_DIR)/01_SpriteJugador.cpp $(SRC_DIR)/SpriteJugador.cpp | $(BIN_DIR)
	$(CXX) $(CXXFLAGS) -I$(INCLUDE_DIR) $^ -o $@ $(LDFLAGS)

run_sprite: sprite
	./$(BIN_DIR)/sprite.exe

.PHONY: all clean run fondo run_fondo sprite run_sprite

# Debug build target for easier memory corruption detection
debug: CXXFLAGS += $(DEBUG_FLAGS)
debug: clean all

run_debug: debug
	./$(BIN_DIR)/main.exe
